### ISSUE TITLE
Seems not work with log4j-mongodb3

### ISSUE THREAD

**Issue by reneelab** [edwgiz/maven-shaded-log4j-transformer#11]
Hi, I added this plugin to my project. It did a good job to solve the log4j configuration confliction in jar.

But after adding log4j-mongodb3 to my project, every time I run my jar it just promote:
2021-01-28 15:17:53,287 main ERROR NoSQL contains an invalid element or attribute "MongoDB3"
2021-01-28 15:17:53,290 main ERROR NoSQL provider not specified for appender [mongoAppender].
2021-01-28 15:17:53,295 main ERROR Null object returned for NoSQL in Appenders.
2021-01-28 15:17:53,300 main ERROR Unable to locate appender "mongoAppender" for logger config "root"

I did add the dependency in pom.xml:

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-mongodb3</artifactId>
            <version>2.14.0</version>
        </dependency>

if I remove the NoSql items， everything goes fine.  Part of my log4j2.xml is:
<Appenders>
    ...
        <NoSQL name="mongoAppender" bufferSize="1">
            <MongoDB3 databaseName="scolog" collectionName="log" server="localhost"
                      port="27017" username="" password=""/>
        </NoSQL>
        <Async name="mongologger" blocking="false" bufferSize="1">
            <AppenderRef ref="mongoAppender"/>
        </Async>

</Appenders>
<Loggers>
        <Root level="info">
            <AppenderRef ref="mongoAppender" />
            <AppenderRef ref="console_out_appender" />
            <AppenderRef ref="console_err_appender" />

        </Root>
</Loggers>

**Comment by reneelab** [comment]
Oh, github filter my codes...
I can not post it here. sorry.

In addition, if I run the main class in Intellij IDEA, everything goes fine.

**Comment by edwgiz** [comment]
Hi @reneelab,
you can send minimal reproducible project to edwgiz@gmail.com, it helps to fix the issue

**Comment by reneelab** [comment]
@edwgiz , I have sent an emil to your address.  Please check it.

**Comment by edwgiz** [comment]
@reneelab please check your pom.xml, it contains several shaded plugin declarations when only one is acceptable

![image](https://user-images.githubusercontent.com/60714309/106353903-ea79d400-62fe-11eb-849a-f210505ffd8b.png)

Also there's no necessity to declare `maven-shaded-log4j-transformer` among project dependencies

**Comment by reneelab** [comment]
1. Oh, I forgot to delete the main class declaration copy from the main project.

2. "Also there's no necessity to declare maven-shaded-log4j-transformer among project dependencies"
But if I comment the dependence of maven-shaded-log4j-transformer, it will not work with the JAR.

<img width="801" alt="1" src="https://user-images.githubusercontent.com/46478609/106354616-1791ab00-632e-11eb-8d9e-1052c6b33521.png">

**Comment by edwgiz** [comment]
Did you rebuild the jar?
In my env commenting out the transformer leads only to lesser jar size
while `/Configuration/Appenders/NoSql/MongoDb3` is recognized correctly

**Comment by reneelab** [comment]
@edwgiz , the problem is solved.
the duplication of the shaded plugin declaration cause the problem.  after deleting other shaded plugin declaration, the problem just fly away.

thx a lot.
