### ISSUE TITLE
Update log4j dependency to 2.16.0 and add tags

### ISSUE THREAD

**Issue by jaw111** [edwgiz/maven-shaded-log4j-transformer#33]

**Comment by amiteswar** [comment]
Can we have 2.16.0 PR published to maven central?

https://github.com/edwgiz/maven-shaded-log4j-transformer/pull/31
https://github.com/edwgiz/maven-shaded-log4j-transformer/pull/32

**Comment by tobijdc** [comment]
Thanks @edwgiz for releasing 2.15.0 so quickly.
We would also love to go to 2.16.0.

**Comment by baekdahl** [comment]
+1 :)

**Comment by mgorovoy** [comment]
I am using 2.15.0 version of the transformer as stopgap, but it would be great if we could get the latest version...

**Comment by justsmithy** [comment]
Is there an ETA for when 2.16.0 will be published to maven central?

**Comment by edwgiz** [comment]
Sonatype publishing to Maven central  failing now,
When it's fixed will publish `2.16.0` ASAP

**Comment by edwgiz** [comment]
Let me mention that plugin isn't affected by the log4j2 vulnerability issue
and `2.15.0` and even earlier plugin version can be used for projects where maven dependencies has log4j2 `2.16.0` one

**Comment by justsmithy** [comment]
@edwgiz our prior versions of log4j prior to 2.16.0 appear to be blacklisted by our internal repository and it seems the maven-shade-plugin is trying to pull down log4j-core 2.15.0.  Is this the expected behavior?  Is there a way to use the maven-shade-plugin using log4j 2.16.0?  Everything we tried seems to suggest we are unable to avoid the maven-shade-plugin from pulling down 2.15.0 of log4j.  Thanks!

**Comment by edwgiz** [comment]
@justsmithy In case of time pressure you can explicitly exclude log4j2 2.15.0 dependencies from the plugin declaration and explicitly add 2.16.0 near by
Hope below fragment helps
```xml
    <dependencies>
        <dependency>
            <groupId>com.github.edwgiz</groupId>
            <artifactId>maven-shade-plugin.log4j2-cachefile-transformer</artifactId>
            <version>2.15.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.16.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.16.0</version>
        </dependency>
    </dependencies>

```

**Comment by edwgiz** [comment]
https://issues.sonatype.org/browse/OSSRH-76200

**Comment by edwgiz** [comment]
The `2.16.0` version was published
https://repo1.maven.org/maven2/io/github/edwgiz/log4j-maven-shade-plugin-extensions/2.16.0/

Please pay attention  the prior transformer declaration in your pom.xml should be rewritten accordingly example in README.md
