### ISSUE TITLE
Unable to find 2.16.0

### ISSUE THREAD

**Issue by SivakumarManickam** [edwgiz/maven-shaded-log4j-transformer#35]
Hi,
  Unable to find 2.16.0 version in maven central repository. Please take a look.
https://mvnrepository.com/artifact/com.github.edwgiz/maven-shade-plugin.log4j2-cachefile-transformer

Thanks.

**Comment by Rorkal** [comment]
Hello, they did change the groupId and artifactId as mentionned in README.md

You can find the new release here : https://mvnrepository.com/artifact/io.github.edwgiz/log4j-maven-shade-plugin-extensions

**Comment by SivakumarManickam** [comment]
My bad, Thanks.
