### ISSUE TITLE
Can not find this dependency on  https://repo.maven.apache.org/maven2 

### ISSUE THREAD

**Issue by Oseenix** [edwgiz/maven-shaded-log4j-transformer#38]
current version has not been publish to maven repository.

**Comment by nddipiazza** [comment]
yes please publish it thanks

**Comment by mgorovoy** [comment]
Have issues with publishing to Maven Central been resolved?

**Comment by mgorovoy** [comment]
It turns out that the artifact for the plugin was renamed:

https://search.maven.org/artifact/io.github.edwgiz/log4j-maven-shade-plugin-extensions/2.17.0/jar

**Comment by nddipiazza** [comment]
yeah good call @mgorovoy 

previously:
https://mvnrepository.com/artifact/com.github.edwgiz/maven-shade-plugin.log4j2-cachefile-transformer

now:
https://mvnrepository.com/artifact/io.github.edwgiz/log4j-maven-shade-plugin-extensions

**Comment by Oseenix** [comment]
It's my fault, It can be found here: https://mvnrepository.com/artifact/io.github.edwgiz/log4j-maven-shade-plugin-extensions/2.17.0
