### ISSUE TITLE
Add support for shade version 3.2.4

### ISSUE THREAD

**Issue by skyghis** [edwgiz/maven-shaded-log4j-transformer#4]
Could you add support for shade version `3.2.4` please.

## Environment

| dependency | version |
|------------------|------------|
| shaded-log4j-transformer | 2.13.2 |
| log4j | 2.13.3 |
| maven-shade-plugin | 3.2.4 |

## Error message

> Receiver class com.github.edwgiz.maven_shade_plugin.log4j2_cache_transformer.PluginsCacheFileTransformer does not define or inherit an implementation of the resolved method 'abstract void processResource(java.lang.String, java.io.InputStream, java.util.List)' of interface org.apache.maven.plugins.shade.resource.ResourceTransformer.

This is probably related to this change: [MSHADE-363](https://issues.apache.org/jira/browse/MSHADE-363)

**Comment by lohcve** [comment]
same issue.

**Comment by edwgiz** [comment]
Yes, sure, thanks for details

**Comment by edwgiz** [comment]
@skyghis, @lohcve 
2.13.3 version was rolled out,
couldn't you please check it in your env by possibility?

**Comment by skyghis** [comment]
Perfect this works in my environment.

Thanks for the very fast fix :fire:.

I'll let you close the issue.

**Comment by lohcve** [comment]
Perfect! thanks!
