### ISSUE TITLE
Log4j v2.17.2

### ISSUE THREAD

**Issue by skyghis** [edwgiz/maven-shaded-log4j-transformer#42]
Could you update the plugin to new log4j version 2.17.2 ?

Thanks for the work !

**Comment by bgong-mdsol** [comment]
We are waiting for this update too, thanks a lot

**Comment by bgong-mdsol** [comment]
@edwgiz is it possible to update the plugin to new log4j version 2.17.2 in this month? Thanks a lot

**Comment by edwgiz** [comment]
Hello @skyghis @bgong-mdsol 

Thank you for the reminder,
please find the latest update rolled out
https://repo1.maven.org/maven2/io/github/edwgiz/log4j-maven-shade-plugin-extensions/2.17.2/

**Comment by edwgiz** [comment]
Btw, there's no necessity to bump plugin immediately along with log4 version,
The old version of plugin should work for a long time due to log4j backward compatibility

**Comment by bgong-mdsol** [comment]
@edwgiz Thanks a lot 💯
