### ISSUE TITLE
Bump to Log4j 2.18.0

### ISSUE THREAD

**Issue by sanyarnd** [edwgiz/maven-shaded-log4j-transformer#43]
https://logging.apache.org/log4j/2.x/changes-report.html#a2.18.0

**Comment by edwgiz** [comment]
Hello @sanyarnd ,
thank you for raising the issue,
please find the latest artifacts on maven central
https://repo.maven.apache.org/maven2/io/github/edwgiz/log4j-maven-shade-plugin-extensions/2.18.0/
